### ISSUE TITLE
Redis chart older versions like 10.5.x are not available on current Bitnami repo

### ISSUE THREAD

**Issue by mohamedmshokry** [PacktPublishing/-Learn-Helm#13]
While following over I noticed that Redis chart used in the book tutorial is available when I tried to download the chart dependencies.
The error will appear like below:

`[root@ks-master-0 helm_work_area]# helm dependency build Learn-Helm/helm-charts/charts/guestbook/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "learnhelm" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "bitnami-pre-2022" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Save error occurred:  could not find : no matching version
Error: could not find : no matching version
`
As per the Carlos comment here https://github.com/bitnami/charts/issues/10545#issuecomment-1144982531
we need to adjust dependencies repository URL to be like beow:

```
dependencies:
  - name: redis
    version: 10.5.x
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
```
